export const strongVerbs = new Set([
  'alcancou', 'alcançou', 'alinhou', 'ampliou', 'analisou', 'aplicou',
  'aprimorou', 'arquitetou', 'assegurou', 'automatizou',
  'capacitou', 'centralizou', 'co-liderou', 'colaborou', 'compilou',
  'completou', 'comunicou', 'concebeu', 'conduziu', 'conquistou',
  'consolidou', 'construiu', 'consultou', 'converteu', 'coordenou',
  'criou', 'cultivou', 'customizou',
  'definiu', 'delegou', 'demonstrou', 'desenvolveu', 'diminuiu',
  'direcionou', 'dirigiu', 'dobrou', 'documentou',
  'economizou', 'editou', 'educou', 'elevou', 'eliminou',
  'empoderou', 'engajou', 'engenheirou', 'entregou', 'escalou',
  'escreveu', 'estabeleceu', 'estruturou', 'executou', 'expandiu',
  'facilitou', 'finalizou', 'formou', 'formulou', 'fundou',
  'gerou', 'gerenciou', 'guiou',
  'idealizou', 'identificou', 'ilustrou', 'implementou', 'implantou',
  'impulsionou', 'aumentou', 'influenciou', 'iniciou', 'inovou',
  'inspirou', 'instituiu', 'integrou', 'introduziu', 'investigou',
  'lancou', 'lançou', 'liderou',
  'manteve', 'mapeou', 'maximizou', 'melhorou', 'mentorou',
  'migrou', 'minimizou', 'modernizou', 'monitorou', 'motivou',
  'navegou', 'negociou',
  'operou', 'organizou', 'orientou', 'otimizou',
  'pilotou', 'pioneirou', 'planejou', 'preparou', 'priorizou',
  'produziu', 'programou', 'projetou', 'promoveu', 'propôs', 'publicou',
  'realizou', 'recrutou', 'redesenhou', 'reduziu', 'refatorou',
  'reformulou', 'reorganizou', 'representou', 'resolveu',
  'reestruturou', 'revitalizou', 'revolucionou',
  'simplificou', 'supervisionou',
  'testou', 'transformou', 'treinou', 'triplicou',
  'unificou',
  'validou', 'viabilizou',
])

export const weakVerbs = new Set([
  'ajudou', 'auxiliou', 'trabalhou', 'fez', 'usou',
  'participou', 'tentou', 'lidou', 'tinha', 'foi',
])
