export const strongVerbs = new Set([
  'achieved', 'accelerated', 'accomplished', 'acquired', 'adapted', 'administered',
  'advanced', 'advocated', 'aligned', 'analyzed', 'applied', 'appointed',
  'architected', 'assembled', 'assessed', 'attained', 'automated',
  'boosted', 'budgeted', 'built',
  'captured', 'centralized', 'championed', 'coached', 'collaborated',
  'communicated', 'compiled', 'completed', 'composed', 'conceived', 'conducted',
  'consolidated', 'constructed', 'consulted', 'converted', 'coordinated',
  'crafted', 'created', 'cultivated', 'customized',
  'decreased', 'defined', 'delegated', 'delivered', 'demonstrated', 'deployed',
  'designed', 'developed', 'devised', 'directed', 'discovered', 'documented',
  'doubled', 'drove',
  'earned', 'edited', 'educated', 'elevated', 'eliminated', 'enabled',
  'encouraged', 'engineered', 'enhanced', 'ensured', 'established',
  'evaluated', 'exceeded', 'executed', 'expanded', 'expedited',
  'facilitated', 'finalized', 'forecasted', 'formulated', 'fostered', 'founded',
  'generated', 'governed', 'grew', 'guided',
  'headed', 'hired',
  'identified', 'illustrated', 'implemented', 'improved', 'increased',
  'influenced', 'initiated', 'innovated', 'inspected', 'inspired',
  'instituted', 'integrated', 'introduced', 'invented', 'investigated',
  'launched', 'led', 'leveraged', 'liaised', 'lowered',
  'maintained', 'managed', 'mapped', 'maximized', 'mentored', 'merged',
  'migrated', 'minimized', 'modeled', 'modernized', 'monitored', 'motivated',
  'navigated', 'negotiated',
  'operated', 'optimized', 'orchestrated', 'organized', 'outperformed', 'overhauled',
  'partnered', 'performed', 'piloted', 'pioneered', 'planned', 'prepared',
  'presented', 'prioritized', 'produced', 'programmed', 'promoted', 'proposed',
  'published', 'purchased',
  'raised', 'ranked', 'realized', 'recommended', 'reconciled', 'recruited',
  'redesigned', 'reduced', 'refactored', 'refined', 'reformed', 'remodeled',
  'reorganized', 'replaced', 'reported', 'represented', 'researched',
  'resolved', 'restructured', 'revamped', 'reviewed', 'revised', 'revolutionized',
  'saved', 'scaled', 'scheduled', 'secured', 'shaped', 'shipped',
  'simplified', 'spearheaded', 'standardized', 'steered', 'streamlined',
  'strengthened', 'structured', 'succeeded', 'supervised', 'surpassed', 'sustained',
  'targeted', 'taught', 'tested', 'trained', 'transformed', 'translated',
  'tripled', 'troubleshot',
  'unified', 'upgraded', 'utilized',
  'validated', 'visualized', 'volunteered',
  'won', 'wrote',
])

export const weakVerbs = new Set([
  'assisted', 'helped', 'worked', 'was', 'did', 'made',
  'used', 'had', 'got', 'tried', 'participated',
  'responsible', 'involved', 'handled', 'dealt', 'showed',
])
